# Uncomment these two line to add support for encoders to your firmware
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Adding ble support
CONFIG_ZMK_BLE=y

# battery
CONFIG_ZMK_BATTERY_REPORTING=y


# add zmk config
CONFIG_ZMK_BOARD_COMPAT=y
